name: Plan & Apply Terraform Changes

env:
  TERRAFORM_VERSION: 1.13.3

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Check Formatting
        run: terraform fmt -check

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Changes
        env:
          EXTERNAL_SECRETS: ${{ secrets.EXTERNAL_SECRETS }}
        run: terraform plan -var="external_secrets=$env.EXTERNAL_SECRETS" -input=false -out=tfplan

      - name: Upload Terraform Plan as Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    if: github.event_name == 'push'
    name: Apply Terraform Changes
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -input=false tfplan

      - name: Terraform Apply
        env:
          EXTERNAL_SECRETS: ${{ secrets.EXTERNAL_SECRETS }}
        run: |
          terraform apply -var="external_secrets=$EXTERNAL_SECRETS" -input=false tfplan